config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'tasks#index'
  resources :tasks
  resources :users, only: [:new, :create, :show, :edit]
  resources :sessions, only: [:new, :create, :destroy]
  namespace :admin do
    resources :users
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :user_name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! if email.present?}
  has_secure_password
  validates :password, length: { minimum: 6}
  has_many :tasks, dependent: :destroy
  before_update :always_one_admin
  before_destroy :one_admin_destroy, if: :admin?


  private
  def always_one_admin
    if User.pluck(:admin).count(true) <= 1 && admin_was && admin == false
      throw(:abort)
    end
  end
  
  def one_admin_destroy
    if User.pluck(:admin).count(true) == 1 
      throw(:abort)
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin_required
  
  def index
    @users = User.all.includes(:tasks)
    
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.admin = false
    if @user.save
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update  
    @user = User.find(params[:id])
    
    if @user.update(user_params)
      redirect_to admin_users_path
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
    @tasks = @user.tasks.order(created_at: :desc)
  end
  
  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to admin_users_path, notice: "ユーザを削除しました！"
    else
      redirect_to admin_users_path, notice: "ユーザ削除に失敗しました"
    end
  end

  private
  def user_params
    params.require(:user).permit(:user_name, :email, :password, :password_confirmation, :admin)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_limitationed, only:[:show]
  skip_before_action :login_required, only:[:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if User.pluck(:admin).include?(true)
      @user.admin = false
    else
      @user.admin = true
    end

    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    
    if params[:sort_end_date]
      @tasks = @user.tasks.order(:end_date).page(params[:page])

    elsif params[:search].present?
      if task_name_params.present? && status_params.present?        
        @tasks = @user.tasks.search_task_name(task_name_params).search_status(status_params).page(params[:page])

      elsif task_name_params.present?        
        @tasks = @user.tasks.search_task_name(task_name_params).page(params[:page])

      elsif status_params.present?
        @tasks = @user.tasks.search_status(status_params).page(params[:page])
      else
        @tasks = @user.tasks.order(created_at: :desc).page(params[:page])
      end
      
    else
      @tasks = @user.tasks.order(created_at: :desc).page(params[:page])
      
    end

  end

  private
  def user_params
    params.require(:user).permit(:user_name, :email, :password, :password_confirmation)
  end

  def task_name_params 
    params[:search][:task_name]
  end

  def status_params
    params[:search][:status]
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper

  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      admin_users_path
    else
      admin_user_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_admin_form.html.erb
<% if user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(user.errors.count, "error") %> prohibited this <%= user.user_name %> from being saved:</h2>
    <ul>
    <% user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: user, local: true, url: choose_new_or_edit ) do |f| %>  
  <%= f.label :user_name %>
  <%= f.text_field :user_name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <% if action == 'edit'%>
    <%= f.label :admin, '管理者権限を与える'%>
    <%= f.check_box :admin %>
    <%= f.submit "更新 "%>
  <% else %>
    <%= f.submit "新規作成"%>
   <% end %>
<% end %>

app/views/admin/users/edit.html.erb
<h1>管理者画面（ユーザー編集）</h1>
<%= render 'admin_form', user: @user, action: 'edit'%>

app/views/admin/users/index.html.erb
<h1>管理者画面</h1>

<%= notice %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ユーザー名</th>
      <th>メールアドレス</th>
      <th>アカウント作成日</th> 
      <th>タスク数</th> 
      <th>管理者権限</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user|%>
      <tr class='user_row'>
        <td><%= user.user_name %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at %></td>  
        <td><%= user.tasks.length %></td>  
        <td><%= '管理者' if user.admin %></td>  
        
        <td><%= link_to "タスク一覧", admin_user_path(user), class: 'btn btn-primary'%></td>
        <td><%= link_to "編集", edit_admin_user_path(user), class: 'btn btn-primary'%></td>
        <td><%= link_to "削除", admin_user_path(user), method: :delete, class: 'btn btn-warning' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users/new.html.erb
<h1>管理者画面（ユーザー登録）</h1>
<%= render 'admin_form', user: @user, action: 'new' %>

app/views/admin/users/show.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>タスク名</th>
      <th>内容</th>
      <th>進捗状況</th>
      <th><%= link_to "優先度", tasks_path(sort_priority: "true") %></th>
      <th>作成者</th>
      <th>作成日</th>
      <th><%= link_to "終了期限", tasks_path(sort_end_date: "true") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

<tbody>
<% @tasks.each do |task|%>
  <tr >
    <td class='task_row'><%= task.task_name %></td>
    <td><%= task.content %></td>
    <td><%= task.status %></td>
    <td><%= task.priority %></td>
    <td><%= task.user.user_name %></td>
    <td><%= task.created_at %></td>
    <td><%= task.end_date %></td>
    <td><%= link_to "詳細", task_path(task), class: 'btn btn-primary'%></td>
    <td><%= link_to "編集", edit_task_path(task), class: 'btn btn-primary'%></td>
    <td><%= link_to "削除", task_path(task), method: :delete, class: 'btn btn-warning' %></td>
  </tr>
<% end %>
</tbody>
</table>