config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'tasks#index'
  resources :tasks
  resources :users, only: [:new, :create, :show, :edit]
  resources :sessions, only: [:new, :create, :destroy]
  namespace :admin do
    resources :users
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManyouKadaiApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
        <div class="container px-4 px-lg-5">

            <% flash.each do |key, value| %>
                <%= content_tag(:div, value, class: "#{key}", class: 'test') %>
            <% end %>
            
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto py-4 py-lg-0">
                    <li class="nav-item"><%= link_to "タスク一覧", tasks_path, class: "nav-link px-lg-3 py-3 py-lg-4" %></li>
                    <li class="nav-item"><%= link_to "タスク追加", new_task_path, class: "nav-link px-lg-3 py-3 py-lg-4" %></li>

                    <% if logged_in? %>
                        <li class="nav-item"><%= link_to "プロフィール", user_path(current_user.id),class: "nav-link px-lg-3 py-3 py-lg-4" %></li>
                        <li class="nav-item"><%= link_to "ログアウト", session_path(current_user.id), method: :delete, class: "nav-link px-lg-3 py-3 py-lg-4" %></li>

                        <% if current_user.admin?%>
                            <li class="nav-item"><%= link_to "管理者ページ", admin_users_path, class: "nav-link px-lg-3 py-3 py-lg-4" %></li>
                            <li class="nav-item"><%= link_to "ユーザー登録", new_admin_user_path, class: "nav-link px-lg-3 py-3 py-lg-4" %></li>
                        <% end %>

                    <% else %>
                        <li class="nav-item"><%= link_to "新規登録", new_user_path, class: "nav-link px-lg-3 py-3 py-lg-4" %></li>
                        <li class="nav-item"><%= link_to "ログイン", new_session_path, class: "nav-link px-lg-3 py-3 py-lg-4" %></li>
                    <% end %>    
                </ul>
            </div>
        </div>
    </nav>
    <%= yield %>
    <footer class="border-top">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <ul class="list-inline text-center">
                        <li class="list-inline-item">
                            <a href="#!">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#!">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#!">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2021</div>
                </div>
            </div>
        </div>
    </footer>
  </body>
</html>